[platformio]
default_envs = node_b
src_dir = firmware

[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+
lib_deps =
  jgromes/RadioLib@^7.3.1
build_flags =
  -D WAITLESS_USE_RADIOLIB
  -I firmware

[env:node_a]
build_src_filter =
  +<shared/>
  +<node_a/>
  -<node_b/>

[env:node_b]
build_src_filter =
  +<shared/>
  +<node_b/>
  -<node_a/>
